# -*- coding: utf-8 -*-
"""Module_Text

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGWVjrEZKzOJsz7vwb3PcmzRLWzodLLw
"""

from sklearn.metrics import classification_report


class modelevaluation():
    def classification_report(self,y_actual,y_pred):
        print(classification_report(y_actual,y_pred))
        print(confusion_matrix(y_actual,y_pred))